### ISSUE TITLE
HakoEveデータベースからイベント情報一覧を取得する

### ISSUE THREAD

**Issue by MasahikoHyodo** [HakoEve/hakoeve_ios#2]
PHPでコーディングする
イベント名、開催日時、開催場所、主催者、詳細文、ジャンル、外部リンク

**Comment by b1011205** [comment]
確認してないけど多分MySQLとの接続はできたと思う
queryと格闘中
土日には終わりそう

**Comment by MasahikoHyodo** [comment]
select * from events;
で全部取得してからPHPで整形するか
それともSQLで整形するかだね

**Comment by b1011205** [comment]
うん
全部取得してからの整形だと面倒くさいから、勉強がてらデータベース結合しようと思っておる

**Comment by b1011205** [comment]
ここでやりたいのって、phpでデータベースからイベント情報引っ張ってくるだけ？
いちおう引っ張ってきたデータをJSON形式に変更して、echoする処理まではもうすぐできそうなんだけど

**Comment by MasahikoHyodo** [comment]
できるならやっちゃっていいかもね。
尊の仕事なくなるけどｗｗ

**Comment by b1011205** [comment]
OK じゃあやっちゃうわー
たける今度お菓子ね

**Comment by MasahikoHyodo** [comment]
:thumbsup:

**Comment by b1011205** [comment]
あ、おもったんだけど、このissueってどの機能のためにイベント情報取得してくるの？
近日開催と、新着のイベントを取得するための処理だったら　タグとか主催者とか詳細文って引っ張ってくる必要ないよね？
タグとかは詳細情報表示のための処理で初めて検索かければいいのでは？
言いたいこと分かるかな汗

**Comment by b1011205** [comment]
↑ だから、それぞれの機能用に分けてクエリ書いたほうがいいと思うんだ

**Comment by MasahikoHyodo** [comment]
とりあえず今回は、
イベント名、開催日時、開催場所
が必要かな

**Comment by b1011205** [comment]
OK 人生で初めてのプルリク送ったから確認をお願いしまっす
