### ISSUE TITLE
ドロワーメニューを追加する

### ISSUE THREAD

**Issue by b1013220** [HakoEve/hakoeve_ios#27]

**Comment by b1011205** [comment]
トップページからドロワーメニューを開くことはできるようになったんだけど、それ以外のページからもドロワーメニュー開けないとアカンよね？汗

**Comment by MasahikoHyodo** [comment]
おつかれ
もちろんそうだねｗ

**Comment by b1011205** [comment]
OK やってみる

**Comment by b1011205** [comment]
↑だれかECSlidingControllerを用いて、トップページ以外の全てのページからメニューを表示する方法わかったら教えて
調べても見つかりゃんせ

**Comment by MasahikoHyodo** [comment]
ブランチあげてもらっていいすか

**Comment by b1011205** [comment]
おｋ

**Comment by b1011205** [comment]
ついかしたよ

 注意：以後は、hakoeve_ios.xcworkspaceからプロジェクトを開かないと、ビルド出来ないので気をつけてください。

**Comment by MasahikoHyodo** [comment]
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

これは何？

**Comment by b1011205** [comment]
うへあ　みんなのろーかるでもやんないといかんのか

コマンドライン上で、
1. sudo gem install cocoapods
2. pod setup
3. pod install
ってやってみて

**Comment by b1011205** [comment]
てか、すっげえナンセンスなやり方だと出来た笑
