### ISSUE TITLE
取得したイベント情報一覧をJSON形式に変換する

### ISSUE THREAD

**Issue by MasahikoHyodo** [HakoEve/hakoeve_ios#3]
PHPでJSON形式に変換し、Swiftからデータを受け取るための準備をする

**Comment by MasahikoHyodo** [comment]
花田のタスクになりました

**Comment by b1011205** [comment]
このタスク自体は、PHP上でjson_encode()する処理を書けばいいので完成したと言っても過言ではないです。#2と密接に関わってくるため、#2が完成次第プルリク送るってことでいいですかね。

**Comment by MasahikoHyodo** [comment]
とりあえずバグがなければブランチ切ってpushしてもいいよ
プルリクはまだだけど

**Comment by b1011205** [comment]
その手があったか汗
もはやプルリクしてしまったから確認してちょ
