### ISSUE TITLE
イベント情報を要求する際にキー名「function」のデータを追加でPOST送信する

### ISSUE THREAD

**Issue by TakeruSaito** [HakoEve/hakoeve_ios#31]

**Comment by b1011205** [comment]
簡単だったよどうしてもやり方わからんかったら俺に聞いて

**Comment by TakeruSaito** [comment]
イベントID : id
イベント名 : event_name
開催場所 : venue_name
開催日時 : date
画像ID : imgId
画像ファイル名 : img_file_name
ジャンルタグ : event_tag
主催者 : event_organizer
連絡先 : contact
詳細 : text
外部リンク : link
っていうふうに変数設定します。

**Comment by b1011205** [comment]
↑そういえばなんでimgIdだけキャメル記法なの？　他全部スネーク記法だからそれに統一したほうが良いと思われ

**Comment by MasahikoHyodo** [comment]
俺がキャメル記法が好き(?)だからかなｗ
imgIdのところだけ俺が書いたからねｗ
俺が書いたSwiftのコードも全部この記法になってるはずｗ
まあどっちかに合わせた方がいいねｗ

**Comment by b1011205** [comment]
そうなのか笑
要検討かな

**Comment by TakeruSaito** [comment]
ところで、動作確認ってどうやったらいいの？
XAMPP動かして、Xcodeの再生ボタンのとこ押すだけ？

**Comment by b1011205** [comment]
yes
