### ISSUE TITLE
イベント詳細画面を実装する

### ISSUE THREAD

**Issue by TakeruSaito** [HakoEve/hakoeve_ios#32]

**Comment by TakeruSaito** [comment]
これってstoryboardいじる必要あるんだよね？
他の人触ってない？

**Comment by MasahikoHyodo** [comment]
新保がいじってる可能性あり

**Comment by TakeruSaito** [comment]
おっふ

**Comment by MasahikoHyodo** [comment]
本人に確認取るべきだね

**Comment by TakeruSaito** [comment]
- 詳細画面中の各コンテンツの表示
- 画像のアス比に合わせた表示
まで出来ました

https://github.com/HakoEve/hakoeve_ios/commit/bfd727848c2a7368854c723da2c39c64fa82783b

**Comment by TakeruSaito** [comment]
文字量に合わせた改行がまだうまく行ってません

**Comment by TakeruSaito** [comment]
改行の関係で画面をスクロールできるようにしたけど、それでも文字量に合わせた開業ができない
(´・ω・`)

**Comment by b1011205** [comment]
どんな状態かわからん汗
一緒に考えて欲しいなら今の状態でいいからbranchあげて

**Comment by TakeruSaito** [comment]
branch上げました。
スクロールの長さは一応適当です。

**Comment by b1011205** [comment]
みたけど、具体的に何をどうしたいんだっけ？

**Comment by TakeruSaito** [comment]
詳細が１行しか表示されないのを、ちゃんと複数行表示させるようにしたい

**Comment by b1011205** [comment]
OK 見れたら見るわ 演習中に完成するようにガンバ
