### ISSUE TITLE
キーワード検索の実装

### ISSUE THREAD

**Issue by b1013220** [HakoEve/hakoeve_ios#38]

**Comment by b1011205** [comment]
>川島くん
サーバ側の処理を書くためのテンプレファイル的なものは作って上げたので、Event側の処理を参考にしつつ頑張ってコード書いてみてー
わからんとこあったら俺に聞いて
(ちなみに実行してないからエラー出るかもわからん汗そこは適宜なおす感じでオナシャス)

**Comment by sKawashima** [comment]
進捗報告です。
ジャンルとキーワードはとりあえず完成しています。日時は「これでいいのか？」程度です。

**Comment by b1011205** [comment]
OKさんきゅ
もし不安であれば今の段階でブランチを上げてくれる？
またはおれに個別に相談してくれい
