### ISSUE TITLE
JSON形式のイベント情報一覧をSwiftで受け取る

### ISSUE THREAD

**Issue by MasahikoHyodo** [HakoEve/hakoeve_ios#4]
簡単なお仕事です。

**Comment by MasahikoHyodo** [comment]
進捗を教えて下さい。

**Comment by b1013220** [comment]
進捗はありません。

**Comment by MasahikoHyodo** [comment]
了解

**Comment by b1013220** [comment]
JSONでの値の受け方を勉強しました。

**Comment by MasahikoHyodo** [comment]
できそうなの？

**Comment by b1013220** [comment]
多分大丈夫だと思います。
なるべく早くやります。

**Comment by b1013220** [comment]
SwiftでJSONデータを受け取るところまで出来ました。
あとはデータをUTF8へ変換し、id, event_nameごとに整形すれば終わると思います。

**Comment by b1011205** [comment]
おれphp側の処理で、UTF8形式のデータをjson形式にエンコードしてるけど、
>あとはデータをUTF8へ変換し
この処理必要？

**Comment by MasahikoHyodo** [comment]
サーバから受け取った値をログに出してみた？

**Comment by b1013220** [comment]
出しました。
一部ですけど、こんな感じででました。

(
        {
        0 = 930;
        1 = "Dabaute Cnoem no-Pyccku!! vol.33 \U304a\U304a\U54b2\U3044\U305f\U30ab\U30ea\U30fc\U30ca";
        2 = "2015-06-22 10:00:00";
        3 = "\U8336\U623f \U6afb\U306e\U4e0b";
        date = "2015-06-22 10:00:00";
        "event_name" = "Dabaute Cnoem no-Pyccku!! vol.33 \U304a\U304a\U54b2\U3044\U305f\U30ab\U30ea\U30fc\U30ca";
        id = 930;
        "venue_name" = "\U8336\U623f \U6afb\U306e\U4e0b";
    },
        {
        0 = 939;
        1 = "\U5e8a\U306b\U6577\U304f\U7d75\U753b\U3000\Uff5e\U30ad\U30ea\U30e0\U3068\U547c\U3070\U308c\U308b\U6577\U7269\U5c55\Uff5e";
        2 = "2015-06-22 10:00:00";
        3 = "\U30ae\U30e3\U30e9\U30ea\U30fc\U6751\U5ca1";
        date = "2015-06-22 10:00:00";
        "event_name" = "\U5e8a\U306b\U6577\U304f\U7d75\U753b\U3000\Uff5e\U30ad\U30ea\U30e0\U3068\U547c\U3070\U308c\U308b\U6577\U7269\U5c55\Uff5e";
        id = 939;
        "venue_name" = "\U30ae\U30e3\U30e9\U30ea\U30fc\U6751\U5ca1";
    },
        {
        0 = 897;
        1 = "\U9aa8\U76e4\U77ef\U6b63\U30b9\U30c8\U30ec\U30c3\U30c1\U6559\U5ba4";
        2 = "2015-06-23 10:00:00";
        3 = "\U51fd\U9928\U5e02\U9752\U5e74\U30bb\U30f3\U30bf\U30fc";
        date = "2015-06-23 10:00:00";
        "event_name" = "\U9aa8\U76e4\U77ef\U6b63\U30b9\U30c8\U30ec\U30c3\U30c1\U6559\U5ba4";
        id = 897;
        "venue_name" = "\U51fd\U9928\U5e02\U9752\U5e74\U30bb\U30f3\U30bf\U30fc";
    },
        {
        0 = 939;
        1 = "\U5e8a\U306b\U6577\U304f\U7d75\U753b\U3000\Uff5e\U30ad\U30ea\U30e0\U3068\U547c\U3070\U308c\U308b\U6577\U7269\U5c55\Uff5e";
        2 = "2015-06-23 10:00:00";
        3 = "\U30ae\U30e3\U30e9\U30ea\U30fc\U6751\U5ca1";
        date = "2015-06-23 10:00:00";
        "event_name" = "\U5e8a\U306b\U6577\U304f\U7d75\U753b\U3000\Uff5e\U30ad\U30ea\U30e0\U3068\U547c\U3070\U308c\U308b\U6577\U7269\U5c55\Uff5e";
        id = 939;
        "venue_name" = "\U30ae\U30e3\U30e9\U30ea\U30fc\U6751\U5ca1";
    },
        {
        0 = 926;
        1 = "\U89b3\U5149\U5ba2\U3068\U306e\U30b3\U30df\U30e5\U30cb\U30b1\U30fc\U30b7\U30e7\U30f3\U306b\U3000\U4f7f\U3048\U308b\U4e2d\U56fd\U8a9e\U4f1a\U8a71";
        2 = "2015-06-23 18:30:00";
        3 = "\U51fd\U9928\U5e02\U5973\U6027\U30bb\U30f3\U30bf\U30fc";
        date = "2015-06-23 18:30:00";
        "event_name" = "\U89b3\U5149\U5ba2\U3068\U306e\U30b3\U30df\U30e5\U30cb\U30b1\U30fc\U30b7\U30e7\U30f3\U306b\U3000\U4f7f\U3048\U308b\U4e2d\U56fd\U8a9e\U4f1a\U8a71";
        id = 926;
        "venue_name" = "\U51fd\U9928\U5e02\U5973\U6027\U30bb\U30f3\U30bf\U30fc";
    },
        {
        0 = 915;
        1 = "\U516c\U4f1a\U5802\U30d7\U30ed\U30e0\U30ca\U30fc\U30c9\U30b3\U30f3\U30b5\U30fc\U30c8";
        2 = "2015-06-26 11:00:00";
        3 = "\U65e7\U51fd\U9928\U533a\U516c\U4f1a\U5802";
        date = "2015-06-26 11:00:00";
        "event_name" = "\U516c\U4f1a\U5802\U30d7\U30ed\U30e0\U30ca\U30fc\U30c9\U30b3\U30f3\U30b5\U30fc\U30c8";
        id = 915;
        "venue_name" = "\U65e7\U51fd\U9928\U533a\U516c\U4f1a\U5802";
    },
        {
        0 = 926;
        1 = "\U89b3\U5149\U5ba2\U3068\U306e\U30b3\U30df\U30e5\U30cb\U30b1\U30fc\U30b7\U30e7\U30f3\U306b\U3000\U4f7f\U3048\U308b\U4e2d\U56fd\U8a9e\U4f1a\U8a71";
        2 = "2015-06-30 18:30:00";
        3 = "\U51fd\U9928\U5e02\U5973\U6027\U30bb\U30f3\U30bf\U30fc";
        date = "2015-06-30 18:30:00";
        "event_name" = "\U89b3\U5149\U5ba2\U3068\U306e\U30b3\U30df\U30e5\U30cb\U30b1\U30fc\U30b7\U30e7\U30f3\U306b\U3000\U4f7f\U3048\U308b\U4e2d\U56fd\U8a9e\U4f1a\U8a71";
        id = 926;
        "venue_name" = "\U51fd\U9928\U5e02\U5973\U6027\U30bb\U30f3\U30bf\U30fc";
    },
        {
        0 = 916;
        1 = "\U516c\U4f1a\U5802\U30d7\U30ed\U30e0\U30ca\U30fc\U30c9\U30b3\U30f3\U30b5\U30fc\U30c8";
        2 = "2015-07-03 11:00:00";
        3 = "\U65e7\U51fd\U9928\U533a\U516c\U4f1a\U5802";
        date = "2015-07-03 11:00:00";
        "event_name" = "\U516c\U4f1a\U5802\U30d7\U30ed\U30e0\U30ca\U30fc\U30c9\U30b3\U30f3\U30b5\U30fc\U30c8";
        id = 916;
        "venue_name" = "\U65e7\U51fd\U9928\U533a\U516c\U4f1a\U5802";
    },
        {
        0 = 897;
        1 = "\U9aa8\U76e4\U77ef\U6b63\U30b9\U30c8\U30ec\U30c3\U30c1\U6559\U5ba4";
        2 = "2015-07-07 10:00:00";
        3 = "\U51fd\U9928\U5e02\U9752\U5e74\U30bb\U30f3\U30bf\U30fc";
        date = "2015-07-07 10:00:00";
        "event_name" = "\U9aa8\U76e4\U77ef\U6b63\U30b9\U30c8\U30ec\U30c3\U30c1\U6559\U5ba4";
        id = 897;
        "venue_name" = "\U51fd\U9928\U5e02\U9752\U5e74\U30bb\U30f3\U30bf\U30fc";
    },
        {
        0 = 926;
        1 = "\U89b3\U5149\U5ba2\U3068\U306e\U30b3\U30df\U30e5\U30cb\U30b1\U30fc\U30b7\U30e7\U30f3\U306b\U3000\U4f7f\U3048\U308b\U4e2d\U56fd\U8a9e\U4f1a\U8a71";
        2 = "2015-07-07 18:30:00";
        3 = "\U51fd\U9928\U5e02\U5973\U6027\U30bb\U30f3\U30bf\U30fc";
        date = "2015-07-07 18:30:00";
        "event_name" = "\U89b3\U5149\U5ba2\U3068\U306e\U30b3\U30df\U30e5\U30cb\U30b1\U30fc\U30b7\U30e7\U30f3\U306b\U3000\U4f7f\U3048\U308b\U4e2d\U56fd\U8a9e\U4f1a\U8a71";
        id = 926;
        "venue_name" = "\U51fd\U9928\U5e02\U5973\U6027\U30bb\U30f3\U30bf\U30fc";
    },
        {
        0 = 916;
        1 = "\U516c\U4f1a\U5802\U30d7\U30ed\U30e0\U30ca\U30fc\U30c9\U30b3\U30f3\U30b5\U30fc\U30c8";
        2 = "2015-07-10 11:00:00";
        3 = "\U65e7\U51fd\U9928\U533a\U516c\U4f1a\U5802";
        date = "2015-07-10 11:00:00";
        "event_name" = "\U516c\U4f1a\U5802\U30d7\U30ed\U30e0\U30ca\U30fc\U30c9\U30b3\U30f3\U30b5\U30fc\U30c8";
        id = 916;
        "venue_name" = "\U65e7\U51fd\U9928\U533a\U516c\U4f1a\U5802";
    },
        {
        0 = 897;
        1 = "\U9aa8\U76e4\U77ef\U6b63\U30b9\U30c8\U30ec\U30c3\U30c1\U6559\U5ba4";
        2 = "2015-07-14 10:00:00";
        3 = "\U51fd\U9928\U5e02\U9752\U5e74\U30bb\U30f3\U30bf\U30fc";
        date = "2015-07-14 10:00:00";
        "event_name" = "\U9aa8\U76e4\U77ef\U6b63\U30b9\U30c8\U30ec\U30c3\U30c1\U6559\U5ba4";
        id = 897;
        "venue_name" = "\U51fd\U9928\U5e02\U9752\U5e74\U30bb\U30f3\U30bf\U30fc";
    },

**Comment by b1013220** [comment]
出しました。
一部ですけど、こんな感じででました。

(
        {
        0 = 930;
        1 = "Dabaute Cnoem no-Pyccku!! vol.33 \U304a\U304a\U54b2\U3044\U305f\U30ab\U30ea\U30fc\U30ca";
        2 = "2015-06-22 10:00:00";
        3 = "\U8336\U623f \U6afb\U306e\U4e0b";
        date = "2015-06-22 10:00:00";
        "event_name" = "Dabaute Cnoem no-Pyccku!! vol.33 \U304a\U304a\U54b2\U3044\U305f\U30ab\U30ea\U30fc\U30ca";
        id = 930;
        "venue_name" = "\U8336\U623f \U6afb\U306e\U4e0b";
    },
        {
        0 = 939;
        1 = "\U5e8a\U306b\U6577\U304f\U7d75\U753b\U3000\Uff5e\U30ad\U30ea\U30e0\U3068\U547c\U3070\U308c\U308b\U6577\U7269\U5c55\Uff5e";
        2 = "2015-06-22 10:00:00";
        3 = "\U30ae\U30e3\U30e9\U30ea\U30fc\U6751\U5ca1";
        date = "2015-06-22 10:00:00";
        "event_name" = "\U5e8a\U306b\U6577\U304f\U7d75\U753b\U3000\Uff5e\U30ad\U30ea\U30e0\U3068\U547c\U3070\U308c\U308b\U6577\U7269\U5c55\Uff5e";
        id = 939;
        "venue_name" = "\U30ae\U30e3\U30e9\U30ea\U30fc\U6751\U5ca1";
    },
