### ISSUE TITLE
受け取ったイベント情報一覧をTableViewに表示する

### ISSUE THREAD

**Issue by MasahikoHyodo** [HakoEve/hakoeve_ios#5]
たぶん簡単なお仕事です。

**Comment by MasahikoHyodo** [comment]
吉田くんのタスク#1が完了したらとりかかります。

**Comment by b1014232** [comment]
花田さんに教えてもらいながら試したんですけど…
実行しようとすると、なんか管理者の名前とパスワードってでてきて…
それ入力しなくてもPC起動することはできます。

**Comment by MasahikoHyodo** [comment]
引き続き待ちます。はやくコミットしてください。

**Comment by b1014232** [comment]
やり方に問題がありました…
もう一回ゼロからやるので
明日までには必ずやります

**Comment by b1014232** [comment]
遅れてホントにすみません。

**Comment by MasahikoHyodo** [comment]
大丈夫だよｗ

**Comment by b1014232** [comment]
あとpushとpullだけです…

**Comment by MasahikoHyodo** [comment]
func response で格納している「date」や「event_name」を別の関数で使う時ってどうすればいいですかね。分かる人いますか

**Comment by MasahikoHyodo** [comment]
@b1013220 新保が書いたソースコードちょっと解説してくれませんかねー
